#!/bin/bash

#============================= Defect parameters ============================#
thr=4
norm="False"
filtro="False"
genome="hg19"
depth=20
quality=30
read_fastq="Paired"
run="False"
#============================= Input Parameters ============================#
while [[ $# -gt 0 ]]; do
	opt="$1"
	shift;
	current_arg="$1"
	case "$opt" in
"-h"|"--help"      ) echo '''
AutoMethyc version 0.1-beta
Usage
	automethyc [options]
Options
	-i --input		Folder with fastq
	-o --output		Output location
	-r --ref		reference genome file
Optional arguments
	-t --threads		Number of threads (default=4)
	-n --normal		Folder with fastq of normals (default=False)
	-g --genome		Genome used for request in UCSC (default=hg19)
		other genomes:
			{hg38, hg19, hg18, hg17, hg16, mm39, mm10, mm9, mm8, mm7}
	-b --bed		File with regions of interest (default=False)
	-d --depth		Minimum depth to consider (default=20)
	-q --quality		Minimum quality (default=30)
	--read		Read type in fastq (default=Paired)
	-rb --run_background	Run on background
''';  exit 1;;
"-i"|"--input"      ) input="$1"; shift;;
"-o"|"--output"      ) output="$1"; shift;;
"-r"|"--reference"      ) ref="$1"; shift;;
"-b"|"--bed"      ) filtro="$1"; shift;;
"-t"|"--threads"      ) thr="$1"; shift;;
"-n"|"--normal"      ) norm="$1"; shift;;
"-g"|"--genome"       ) genome="$1"; shift;;
"-q"|"--quality"       ) quality="$1"; shift;;
"-d"|"--depth"       ) depth="$1"; shift;;
"-rb"|"--run_background"       ) run="True"; shift;;
"--read"       ) read_fastq="$1"; shift;;
	esac
done

#============================= Pathways extraction ============================#
dir=$(pwd) ; dir_home=$(echo $dir | cut -d'/' -f2)

# Clasificación de rutas absolutas y relativas
pathway_val () {
	if [ "$1" = "False" ]; then
		var=$1
	elif [ "$(echo $1 | cut -d'/' -f2)" != "$dir_home" ]; then #ruta relativa
		var=$dir/$1
	else #ruta absoluta
		var=$1
	fi
}

pathway_val $input ; input=$var
pathway_val $output ; output=$var
pathway_val $ref ; ref=$var
pathway_val $norm ; norm=$var
pathway_val $filtro ; filtro=$var

if [ "$run" = "False" ]; then
	docker run -v /${dir_home}:/${dir_home} -it ambrizbiotech/automethyc automethyc -i $input -o $output -r $ref -n $norm -t $thr -b $filtro -g $genome -q $quality -d $depth
else
	docker run -v /${dir_home}:/${dir_home} -d ambrizbiotech/automethyc automethyc -i $input -o $output -r $ref -n $norm -t $thr -b $filtro -g $genome -q $quality -d $depth
fi
