#!/bin/bash

#Defect values
thr=4
norm="False"
filtro="False"
genome="hg19"
depth=20

# Options
while [[ $# -gt 0 ]]; do
opt="$1"
shift;
current_arg="$1"
case "$opt" in
"-h"|"--help"      ) echo '''
AutoMethyc version 0.0.2-beta
Usage
	AutoMethyc [options]
Options
	-i --input		Folder with fastq
	-o --output		Output location
	-r --ref		Folder with references
Optional arguments
	-t --threads		Number of threads (default=4)
	-n --normal		Folder with fastq of normals (default=False)
	-g --genome		Reference genome (default=hg19)
		other genomes:
			{hg38, hg19, hg18, hg17, hg16, mm39, mm10, mm9, mm8, mm7}
	-f --filtro		File with regions of interest (default=False)
	-d --depth		Minimum depth to consider (default=20)
''';  exit 1;;
"-i"|"--input"      ) input="$1"; shift;;
"-o"|"--output"      ) output="$1"; shift;;
"-r"|"--ref"      ) ref="$1"; shift;;
"-f"|"--filtro"      ) filtro="$1"; shift;;
"-t"|"--threads"      ) thr="$1"; shift;;
"-n"|"--normal"      ) norm="$1"; shift;;
"-g"|"--genome"       ) genome="$1"; shift;;

	esac
done

# Organizando el Output
mkdir $output/CSV
mkdir $output/HTML
mkdir $output/Bismark
mkdir $output/HTML/Bismark_report

echo '#----------------------Parameters---------------------------#'
echo '		input: ' $input
echo '		output: ' $output
echo '		ref: '	$ref
echo '		filtro: ' $filtro
echo '		threads: ' $thr
echo '		normal: ' $norm
echo '		genome: ' $genome
echo '		depth: ' $depth
echo '#-----------------------------------------------------------#'

if [ "$norm" = "False" ]; then
	if [ "$filtro" = "False" ]; then
		echo 'usando la version sin normales y sin filtro'

		BuclePipeline.sh $input $output $ref $thr

		# Filtrado por profundidad
		DepthCord.sh $output/results/06_bedGraph $output/CSV $depth

		# descomprime y renombra los archivos por ID
		rename.sh $output/results/06_bedGraph
		# Construcción del merge
		allmerge.sh $output/results/06_bedGraph $output 'Sample'
	

		python /usr/bin/Oncoprint_wf.py $output/merge.csv $output


		multiqc $output/results/02_fastq_trimmed/*
		mv multiqc* $output/HTML

		mv $output/results $output/Bismark

				
		mv $output/results/results_html/* $output/HTML/Bismark_report
		mv $output/*csv $output/CSV
		rm -rf $output/tmp

		python /usr/bin/WebScrapping.py $output/CSV/Oncoprint_wf.csv hg19 $output/CSV True

		python /usr/bin/Report_HTML_wf.py $output/CSV/Oncoprint_wf.csv $output/Count.csv $output/HTML $output/CSV/StatusCpG.csv
	else
		echo 'usando la version sin normales y con filtro'

				BuclePipeline.sh $input $output $ref $thr
				# Filtrado por profundidad
				DepthCord.sh $output/results/06_bedGraph $output/CSV $depth
				# descomprime y renombra los archivos por ID
				rename.sh $output/results/06_bedGraph
				# Construcción del merge
				allmerge.sh $output/results/06_bedGraph $output 'Sample'
				# Aplicacion de filtros
				python /usr/bin/Filter.py $output/merge.csv $filtro $output

				python /usr/bin/Oncoprint.py $output/Filtered.csv $output

				multiqc $output/results/02_fastq_trimmed/*
				mv multiqc* $output/HTML

				mv $output/results $output/Bismark

				
				mv $output/results/results_html/* $output/HTML/Bismark_report
				mv $output/*csv $output/CSV
				rm -rf $output/tmp

				python /usr/bin/CountUF.py $output/CSV/merge.csv $output/CSV/Filtered.csv $output/CSV
				python /usr/bin/WebScrapping.py $filtro $genome $output/CSV False

				python /usr/bin/Report_HTML.py $output/CSV/Oncoprint.csv $output/CSV/OncoprintPromedio.csv $output/CSV/Count.csv $output/CSV/NotLoc.csv $output/HTML $output/CSV/CountUF.csv $output/CSV/StatusCpG.csv
	fi
else
	if [ "$filtro" = "False" ]; then

		echo 'usando la version con normales y sin filtro'

				mkdir $output/norm
				mkdir $output/samples


				echo '---------------Normal Samples------------------'
				BuclePipeline.sh $norm $output/norm $ref $thr
				# Filtrado por profundidad
				DepthCord.sh $output/norm/results/06_bedGraph $output/CSV $depth
				# descomprime y renombra los archivos por ID
				rename.sh $output/norm/results/06_bedGraph
				# Construcción del merge
				allmerge.sh $output/norm/results/06_bedGraph $output/norm 'Normal'
				
				
				multiqc $output/norm/results/02_fastq_trimmed/*

				mv multiqc_report.html $output/HTML/multiqc_report_normals.html
				mv multiqc_data $output/HTML/multiqc_data_normals


				echo '------------------Samples---------------------'
				BuclePipeline.sh $input $output/samples $ref $thr
				# Filtrado por profundidad
				DepthCord.sh $output/samples/results/06_bedGraph $output $depth
				rename.sh $output/samples/results/06_bedGraph
				allmerge.sh $output/samples/results/06_bedGraph $output/samples 'Sample'

				echo 'Joining in one file the samples and normals'
				
				awk '(NR == 1) || (FNR > 1)' $output/norm/merge.csv $output/samples/merge.csv > $output/merge.csv
				awk '(NR == 1) || (FNR > 1)' $output/CountUF_depth.csv $output/CSV/CountUF_depth.csv > $output/CSV/CountUF_depth_merge.csv
				rm -rf $output/CountUF_depth.csv $output/CSV/CountUF_depth.csv

				echo 'Done merge samples and normals'

				python /usr/bin/Oncoprint_wf.py $output/merge.csv $output

				multiqc $output/samples/results/02_fastq_trimmed/*
				mv multiqc_report.html $output/HTML/multiqc_report_samples.html
				mv multiqc_data $output/HTML/multiqc_data_samples
				
				# Organizacion Output
				mv $output/*csv $output/CSV
				mv $output/samples $output/Bismark
				mv $output/norm $output/Bismark

				rm -rf $output/Bismark/norm/tmp
				rm -rf $output/Bismark/samples/tmp

				
				python /usr/bin/Norm_wf.py $output/CSV/Oncoprint_wf.csv $output/CSV

				python /usr/bin/PCA.py $output/CSV/OncoprintNorm.csv $output/CSV

				python /usr/bin/WebScrapping.py $output/CSV/Oncoprint_wf.csv hg19 $output/CSV True


				python /usr/bin/Report_HTML_norm_wf.py $output $output/HTML
	else
				echo 'usando la version con normales y con filtro'

				echo 'You are using normals'
				mkdir $output/norm
				mkdir $output/samples


				echo '---------------Normal Samples------------------'
				BuclePipeline.sh $norm $output/norm $ref $thr
				# Filtrado por profundidad
				DepthCord.sh $output/norm/results/06_bedGraph $output/CSV $depth
				# descomprime y renombra los archivos por ID
				rename.sh $output/norm/results/06_bedGraph
				# Construcción del merge
				allmerge.sh $output/norm/results/06_bedGraph $output/norm 'Normal'
				# Aplicacion de filtros
				python /usr/bin/Filter.py $output/norm/merge.csv $filtro $output/norm

				multiqc $output/norm/results/02_fastq_trimmed/*

				mv multiqc_report.html $output/HTML/multiqc_report_normals.html
				mv multiqc_data $output/HTML/multiqc_data_normals



				echo '------------------Samples---------------------'
				BuclePipeline.sh $input $output/samples $ref $thr
				# Filtrado por profundidad
				DepthCord.sh $output/samples/results/06_bedGraph $output $depth
				rename.sh $output/samples/results/06_bedGraph
				allmerge.sh $output/samples/results/06_bedGraph $output/samples 'Sample'
				python /usr/bin/Filter.py $output/samples/merge.csv $filtro $output/samples

				echo 'Joining in one file the samples and normals'
				
				awk '(NR == 1) || (FNR > 1)' $output/norm/Filtered.csv $output/samples/Filtered.csv > $output/Filtered.csv

				awk '(NR == 1) || (FNR > 1)' $output/norm/Count.csv $output/samples/Count.csv > $output/Count.csv

				awk '(NR == 1) || (FNR > 1)' $output/norm/NotLoc.csv $output/samples/NotLoc.csv > $output/NotLoc.csv

				awk '(NR == 1) || (FNR > 1)' $output/norm/merge.csv $output/samples/merge.csv > $output/merge.csv

				awk '(NR == 1) || (FNR > 1)' $output/CountUF_depth.csv $output/CSV/CountUF_depth.csv > $output/CSV/CountUF_depth_merge.csv
				rm -rf $output/CountUF_depth.csv $output/CSV/CountUF_depth.csv


				echo 'Done merge samples and normals'


				python /usr/bin/Oncoprint.py $output/Filtered.csv $output

				multiqc $output/samples/results/02_fastq_trimmed/*
				mv multiqc_report.html $output/HTML/multiqc_report_samples.html
				mv multiqc_data $output/HTML/multiqc_data_samples
				
				# Organizacion Output
				mv $output/*csv $output/CSV
				mv $output/samples $output/Bismark
				mv $output/norm $output/Bismark

				rm -rf $output/Bismark/norm/tmp
				rm -rf $output/Bismark/samples/tmp

				python /usr/bin/Norm.py $output/CSV/OncoprintRellenado.csv $output/CSV/OncoprintPromedio.csv $output/CSV

				python /usr/bin/PCA.py $output/CSV/OncoprintNorm.csv $output/CSV

				python /usr/bin/CountUF.py $output/CSV/merge.csv $output/CSV/Filtered.csv $output/CSV

				python /usr/bin/WebScrapping.py $filtro $genome $output/CSV False

				python /usr/bin/Report_HTML_norm.py $output $output/HTML
	fi
fi

#Rscript /usr/bin/Oncoprint.R $output/OncoprintRellenado.csv $output/all_sites.png

#Rscript /usr/bin/OncoprintPromedio.R $output/OncoprintPromedio.csv $output/mean.png


echo 'Done Report HTML' 

echo 'DONE'
