#!/bin/bash

#============================= Input Parameters ============================#
input=$1
output=$2
genome=$3
thr=$4
quality=$5
paired=$6
PREFIX=one_mismatch
FolderOutput=$7
#============================= Make directories ============================#

mkdir $output/tmp
mkdir $output/tmp/02_fastq_trimmed
mkdir $output/tmp/03_aligned
mkdir $output/tmp/04_deduplicated
mkdir $output/tmp/05_bismark_extractor
mkdir $output/tmp/06_bedGraph

mkdir $output/Bismark/$FolderOutput
mkdir $output/Bismark/$FolderOutput/fastq_trimmed
mkdir $output/Bismark/$FolderOutput/aligned
mkdir $output/Bismark/$FolderOutput/deduplicated
mkdir $output/Bismark/$FolderOutput/bismark_extractor
mkdir $output/Bismark/$FolderOutput/bedGraph
mkdir $output/Bismark/$FolderOutput/html_reports

#============================= Genome Conversion ============================#

genome_bisulfito=$genome/Bisulfite_Genome
if [ -d "$genome_bisulfito"  ]
then 
				echo 'starting with sample processing'
else
        echo 'starting with bismark_genome_preparation'
				bismark_genome_preparation $genome --parallel $(($thr/2))
fi

#============================= Run pipeline ============================#

array=($(ls $input/*.f*))
tLen=${#array[@]}

if [ "$paired" = "Paired" ]; then
        for (( i=0; i<${tLen}; i=i+2));
        do
                FQ1=${array[$i]}
                FQ2=${array[$i+1]}
                OUT=$output/tmp/02_fastq_trimmed

		echo "trim_galore start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                trim_galore --quality $quality --gzip --paired --fastqc \
                        --illumina --output_dir ${OUT} \
                        --cores $thr ${FQ1} ${FQ2}

                echo '==================== done trim_galore ===================='
               
                FQ1=$output/tmp/02_fastq_trimmed/*val_1.fq.gz
                FQ2=$output/tmp/02_fastq_trimmed/*val_2.fq.gz
                OUT=$output/tmp/03_aligned

		echo "bismark start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bismark --bowtie2 --parallel $(($thr/2)) --bam --fastq \
                        --output_dir ${OUT} \
                        --prefix ${PREFIX} \
                        --genome_folder ${genome} \
                        -1 ${FQ1} -2 ${FQ2}

                echo '===================== done bismark ====================='

                BAM_IN=$output/tmp/03_aligned/one_mismatch*pe.bam
                OUT=$(ls ${BAM_IN})
    echo "samtools sort start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                samtools sort -n ${BAM_IN} -o ${OUT%.bam}_sorted.bam

                echo '===================== done samtools ====================='

                BAM_IN=${BAM_IN%.bam}_sorted.bam
                OUT=$output/tmp/03_aligned
    echo "filter_non_conversion start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                filter_non_conversion ${BAM_IN}
                
                mv one_mismatch*filtered.bam ${OUT}

                echo '=============== done filter non conversion =============='

                BAM_IN=$output/tmp/03_aligned/one_mismatch*filtered.bam
                OUT=$output/tmp/04_deduplicated
    echo "deduplicate_bismark start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                deduplicate_bismark ${BAM_IN} --output_dir ${OUT}

                echo '=================== done deduplicate ===================='

                BAM_IN=$output/tmp/03_aligned/one_mismatch*pe.bam
                OUT=$output/tmp/05_bismark_extractor/

		echo "bismark_methylation_extractor start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bismark_methylation_extractor --paired-end \
                        --gzip \
                        --bedGraph \
                        --parallel $(($thr/2)) \
                        --output ${OUT} \
                        --genome_folder ${genome} \
                        ${BAM_IN}

                echo '========== done bismark_methylation_extractor =========='
               
                IN=$output/tmp/03_aligned/one_mismatch*pe.bam
                OUT=$output/tmp/04_deduplicated

		echo "bam2nuc start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bam2nuc --genome_folder ${genome} --dir ${OUT} ${IN} 

                echo '===================== done bam2nuc ======================'

		echo "bismark2report start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bismark2report --alignment_report $output/tmp/03_aligned/one_mismatch*report.txt \
                        --splitting_report $output/tmp/05_bismark_extractor/one_mismatch*splitting_report.txt \
                        --mbias_report $output/tmp/05_bismark_extractor/one_mismatch*.M-bias.txt \
                        --nucleotide_report $output/tmp/04_deduplicated/one_mismatch*.nucleotide_stats.txt

                echo '================== done bismark2report =================='

                mv $output/tmp/02_fastq_trimmed/* $output/Bismark/$FolderOutput/fastq_trimmed
                mv $output/tmp/03_aligned/* $output/Bismark/$FolderOutput/aligned
                mv $output/tmp/04_deduplicated/*.bam $output/Bismark/$FolderOutput/deduplicated
                mv $output/tmp/04_deduplicated/*.txt $output/Bismark/$FolderOutput/deduplicated
                mv $output/tmp/05_bismark_extractor/*.txt.gz $output/Bismark/$FolderOutput/bismark_extractor
                mv $output/tmp/05_bismark_extractor/*.txt $output/Bismark/$FolderOutput/bismark_extractor
                mv  $output/tmp/05_bismark_extractor/*.bedGraph.gz $output/Bismark/$FolderOutput/bedGraph
                mv  $output/tmp/05_bismark_extractor/*.bismark.cov.gz $output/Bismark/$FolderOutput/bedGraph  
                mv *.html $output/Bismark/$FolderOutput/html_reports
        done
else
        for (( i=0; i<${tLen}; i=i+1));
        do
                echo using single read
                FQ1=${array[$i]}
                echo processing ${FQ1}

                OUT=$output/tmp/02_fastq_trimmed

		echo "trim_galore start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                trim_galore --quality $quality --gzip --fastqc \
                        --illumina --output_dir ${OUT} \
                        --cores $thr ${FQ1}

                echo '=================== done trim_galore ==================='
 
                FQ1=$output/tmp/02_fastq_trimmed/*_trimmed.fq.gz
                OUT=$output/tmp/03_aligned

		echo "bismark start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bismark --bowtie2 --parallel $(($thr/2)) --bam --fastq \
                        --output_dir ${OUT} \
                        --prefix ${PREFIX} \
                        --genome_folder ${genome} \
                        ${FQ1}

                echo '===================== done bismark ====================='

                BAM_IN=$output/tmp/03_aligned/one_mismatch*pe.bam
                OUT=$(ls ${BAM_IN})
    echo "samtools sort start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                samtools sort -n ${BAM_IN} -o ${OUT%.bam}_sorted.bam

                echo '===================== done samtools ====================='

                BAM_IN=${BAM_IN%.bam}_sorted.bam
                OUT=$output/tmp/03_aligned
    echo "filter_non_conversion start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                filter_non_conversion ${BAM_IN}
                
                mv one_mismatch*filtered.bam ${OUT}

                echo '=============== done filter non conversion =============='

                BAM_IN=$output/tmp/03_aligned/one_mismatch*filtered.bam
                OUT=$output/tmp/04_deduplicated
    echo "deduplicate_bismark start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                deduplicate_bismark ${BAM_IN} --output_dir ${OUT}

                echo '=================== done deduplicate ===================='

                BAM_IN=$output/tmp/03_aligned/one_mismatch*pe.bam
                OUT=$output/tmp/05_bismark_extractor/

		echo "bismark_methylation_extractor start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bismark_methylation_extractor --paired-end \
                        --gzip \
                        --bedGraph \
                        --parallel $(($thr/2)) \
                        --output ${OUT} \
                        --genome_folder ${genome} \
                        ${BAM_IN}

                echo '========== done bismark_methylation_extractor =========='
               
                IN=$output/tmp/03_aligned/one_mismatch*pe.bam
                OUT=$output/tmp/04_deduplicated

		echo "bam2nuc start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bam2nuc --genome_folder ${genome} --dir ${OUT} ${IN} 

                echo '===================== done bam2nuc ======================'

		echo "bismark2report start at: $(date +'%H:%M:%S')" >> $output/execution_time.txt
                bismark2report --alignment_report $output/tmp/03_aligned/one_mismatch*report.txt \
                        --splitting_report $output/tmp/05_bismark_extractor/one_mismatch*splitting_report.txt \
                        --mbias_report $output/tmp/05_bismark_extractor/one_mismatch*.M-bias.txt \
                        --nucleotide_report $output/tmp/04_deduplicated/one_mismatch*.nucleotide_stats.txt

                echo '================== done bismark2report =================='

                mv $output/tmp/02_fastq_trimmed/* $output/Bismark/$FolderOutput/fastq_trimmed
                mv $output/tmp/03_aligned/* $output/Bismark/$FolderOutput/aligned
                mv $output/tmp/04_deduplicated/*.bam $output/Bismark/$FolderOutput/deduplicated
                mv $output/tmp/04_deduplicated/*.txt $output/Bismark/$FolderOutput/deduplicated
                mv $output/tmp/05_bismark_extractor/*.txt.gz $output/Bismark/$FolderOutput/bismark_extractor
                mv $output/tmp/05_bismark_extractor/*.txt $output/Bismark/$FolderOutput/bismark_extractor
                mv  $output/tmp/05_bismark_extractor/*.bedGraph.gz $output/Bismark/$FolderOutput/bedGraph
                mv  $output/tmp/05_bismark_extractor/*.bismark.cov.gz $output/Bismark/$FolderOutput/bedGraph  
                mv *.html $output/Bismark/$FolderOutput/html_reports

        done
fi
rm -rf $output/tmp/
echo '================= done bismark_rounded =================='
