#!/usr/bin/env python3
# coding: utf-8
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
import pandas as pd
import numpy as np
import sys

df_type_allsites = pd.read_csv(sys.argv[1])
df_gene = pd.read_csv(sys.argv[2])
output = sys.argv[3]

columns_type = list(df_type_allsites.columns)
columns_type = columns_type[2:len(columns_type)]
columns_gene = list(df_gene.columns)
columns_gene = columns_gene[2:len(columns_gene)]

df_type = pd.melt(df_type_allsites, id_vars=['ID', 'Type'], value_vars=columns_type)
df_gene = pd.melt(df_gene, id_vars=['ID', 'Type'], value_vars=columns_gene)

print(df_type)
print(df_gene)

df_type.to_csv(output+'/Boxplot_all_sites.csv')
df_gene.to_csv(output+'/Boxplot_mean_gene.csv')

