#!/bin/bash

input=$1
output=$2
dep=$3

gzip -d $input/*.gz

echo 'filtered,unfiltered,depth_mean' > $output/CountUF_depth.csv
echo '---INPUT----'
echo $(ls $input)

for i in $input/*.cov;
do
	x=${i%_S*}
	x=${x##*/}
	prefix='one_mismatch.'
	ID=${x/#$prefix}

	Depth $i $output $dep $ID

done
