#!/usr/bin/env python3
#import os
#os.environ['OPENBLAS_NUM_THREADS'] = '1'

import sys
import pandas as pd

inp = sys.argv[1]
merge = sys.argv[2]
ID = sys.argv[3]
contador = int(sys.argv[4])

df = open(inp)
lines = df.readlines()

df = pd.DataFrame(lines)
lenght = len(df)
df = df[0].str.split('\t',expand=True)

# Revision de si es 12 o 13???
cut = 13

df.columns = df.iloc[cut]
df = df.drop(list(range(0,cut+1,1)))

df = df.rename(columns = {'90th Percentile\n':'90th Percentile'})

print(df)

if contador % 2 == 0:
    contador = 2
else:
    contador = 1

for i in df['#Base']:
    if  i == '>>END_MODULE\n':
        break
    else:
        cut = cut+1

df = df.drop(list(range(cut,lenght,1)))

df['ID'] = [ID + '_' + str(contador)] * len(df)

df_bd = pd.read_csv(merge)

df_fastqc = pd.concat([df_bd, df],  sort=False)
df_fastqc = df_fastqc.set_index('#Base')

df_fastqc.to_csv(merge)
