#!/bin/bash

fastqc_folder=$1
output=$2

original=$(pwd)

echo '=================== joining fastqc files ==================='

cd $fastqc_folder
unzip '*.zip'

cd $original
echo '#Base,Mean,Median,Lower Quartile,Upper Quartile,10th Percentile,90th Percentile,ID'> $output/fastqc_raw_data.csv

#LISTARLOS DESDE AQUI
array=($(find $fastqc_folder -maxdepth 1 -type d | sort -t '\0' -n))
tLen=${#array[@]}

for (( i=1; i<${tLen}; i=i+1));
do
  x=${array[$i]%_S*}; ID=${x##*/}
  fastqc_read ${array[$i]}/fastqc_data.txt $output/fastqc_raw_data.csv $ID $i
done
echo '==================== done fastqc_extract ==================='
