#!/usr/bin/env python3
#import os
#os.environ['OPENBLAS_NUM_THREADS'] = '1'

import sys
import pandas as pd
import numpy as np
from tqdm import trange as tr
from tqdm import tqdm as td
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

print ('==================== starting filtering ====================')
#----------------------------Data------------------------------
df = pd.read_csv(sys.argv[1])
dfF = pd.read_csv(sys.argv[2])
OutputFilter = sys.argv[3]

print("Done read csv")
#----------------------------InLoc------------------------------
df_bd = pd.DataFrame()
lst = []
for c,s,ID in zip(df.Chr, df.Start, df.ID):
    dF_i = dfF[dfF['Chr'] == c]
    for sF,eF,Gene in zip(dF_i.Start, dF_i.End, dF_i.Gene):
        if s in range(sF, eF+1, 1):
            db_i = df[(df['Start'] == s) & (df['ID'] == ID)]
            lst.append(Gene)
            df_bd = pd.concat([df_bd, db_i])
df_bd['Gene'] = lst
df_filtrado = df_bd

ID = df_filtrado['ID'].value_counts()

df_filtrado = df_filtrado.set_index('ID')

print('on-targets: ')
print(df_filtrado)

df_filtrado.to_csv(OutputFilter+"/filtered_target.csv")

ID = pd.DataFrame(ID)
ID.to_csv(OutputFilter+"/count_targets.csv")
print(ID)

#-----------------------NotLoc--------------------------
#ID count_filtered
count_merge = pd.DataFrame(df['ID'].value_counts()); count_merge.columns = ['Frequencies']
df_NotLoc = count_merge.join(ID).reset_index()
df_NotLoc['count'] = df_NotLoc['Frequencies'] - df_NotLoc['count']
df_NotLoc = df_NotLoc[['ID', 'count']]

print('off-targets: ')
print(df_NotLoc)

df_NotLoc.to_csv(OutputFilter+"/off_targets.csv", index = False)
print ('==================== done filter_target ====================')
