#!/usr/bin/env python3
#import os
#os.environ['OPENBLAS_NUM_THREADS'] = '1'

import sys
import pandas as pd
import numpy as np
from tqdm import trange as tr
from tqdm import tqdm as td
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

print ('==================== starting filtering ====================')
#----------------------------Data------------------------------
df = pd.read_csv(sys.argv[1], index_col=False)
dfF = pd.read_csv(sys.argv[2])
OutputFilter = sys.argv[3]

print("Done read csv")
print(df)
print(dfF)

df['Start'] = df['Start'].apply(int) ;df['End'] = df['End'].apply(int)
dfF['Start'] = dfF['Start'].apply(int) ;dfF['End'] = dfF['End'].apply(int)


#----------------------------InLoc------------------------------
df_filtrado = df[df.apply(lambda row: any((row['Chr'] == dfF['Chr']) & (row['Start'] >= dfF['Start']) & (row['Start'] <= dfF['End'])), axis=1)]

# Añadir la columna del gen correspondiente
def get_gene(row, df2):
    genes = df2[(df2['Chr'] == row['Chr']) &
                (df2['Start'] <= row['Start']) &
                (df2['End'] >= row['Start'])]['Gene']
    return genes.iloc[0] if not genes.empty else None

df_filtrado['Gene'] = df_filtrado.apply(lambda row: get_gene(row, dfF), axis=1)

print(df_filtrado)

ID = df_filtrado[['ID', 'Type']].value_counts()
df_filtrado = df_filtrado.set_index('ID')

print('on-targets: ')
print(df_filtrado)

df_filtrado.to_csv(OutputFilter+"/filtered_target.csv")

ID = pd.DataFrame(ID); ID.columns = ['count']
ID.to_csv(OutputFilter+"/count_targets.csv")
print(ID)

#-----------------------NotLoc--------------------------
#ID count_filtered
count_merge = pd.DataFrame(df[['ID', 'Type']].value_counts()); count_merge.columns = ['Frequencies']
df_NotLoc = count_merge.join(ID).reset_index()
df_NotLoc['count'] = df_NotLoc['Frequencies'] - df_NotLoc['count']
df_NotLoc = df_NotLoc[['ID', 'Type', 'count']]

print('off-targets: ')
print(df_NotLoc)

df_NotLoc.to_csv(OutputFilter+"/off_targets.csv", index = False)
print ('==================== done filter_target ====================')
