#!/bin/bash

input=$1
output=$2
depth=$3

gzip -d $input/*.gz

echo 'filtered,unfiltered,depth_mean' > $output/count_depth_${depth}_pass.csv
echo '==================== filtering by depth ===================='

for i in $input/*.cov;
do
	x=${i%_S*}; x=${x##*/}; prefix='one_mismatch.'; ID=${x/#$prefix}
	echo $ID
	read_depth $i $output $depth $ID
done
echo '==================== done filter_depth ===================='
