#!/usr/bin/env python3
#import os
#os.environ['OPENBLAS_NUM_THREADS'] = '1'

import pandas as pd
import numpy as np
import plotly.express as px
from IPython.display import HTML
import sys
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import re

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

from modules_plotly import *
from modules_html import *

input_folder = sys.argv[1]
Output = sys.argv[2]

norm = sys.argv[3]
depth = sys.argv[4]

print ('======================= making HTML report ======================')

c = input_folder + '/command_options.txt'
depth = input_folder + '/CSV/count_depth_' + str(depth) + '_pass.csv'
Count = input_folder+'/CSV/count_targets.csv'
NotLoc = input_folder+'/CSV/off_targets.csv'
Oncoprint_All = input_folder+'/CSV/matrix_filtered_target.csv'
Oncoprint_mean = input_folder+'/CSV/matrix_mean_gene.csv'
cgi = input_folder+ '/CSV/cgi_features.csv'
fastqc = input_folder + '/CSV/fastqc_raw_data.csv'
OncoprintNorm = input_folder+'/CSV/matrix_filtered_target_normalized.csv'
OncoprintMeanNorm = input_folder + '/CSV/matrix_mean_gene_normalized.csv'
PCA_data = input_folder + '/CSV/pca_vectors.csv'
boxplot_csv = input_folder + '/CSV/filtered_target_normalized.csv'
filtered_target = input_folder + '/CSV/filtered_target.csv'
bed_genes = input_folder + '/CSV/annotated_regions.csv'
mean_gene_normalized = input_folder + '/CSV/mean_gene_normalized.csv'
snv_count = input_folder + '/CSV/snv_count.csv'
volcano = input_folder  + '/CSV/volcano_plot_data.csv'

#=======================fastqc======================#
df = pd.read_csv(fastqc)
fig_fastqc = plot_fastqc(df)

#=======================Depth======================#
df = pd.read_csv(depth)
fig_depth = plot_depth(df, norm)

#========================All=========================#
sites_bed = pd.read_csv(cgi)
df = pd.read_csv(Oncoprint_All)
df = df.drop(['Unnamed: 2'], axis=1)
group = pd.DataFrame(df.iloc[0]).drop(['ID', 'Unnamed: 1'])
group[0] = group[0].replace({'controls':0, 'cases':1})
df = df.drop(df.index[[0,1]])
df = df.rename(columns = {'Unnamed: 1':'Start', 'ID':'Chr'})
fig_all = plot_all(sites_bed, df, group)

#========================Mean=======================#
df = pd.read_csv(Oncoprint_mean)
fig_mean = plot_mean(df)

#=====================Off-target====================#
on_targets = pd.read_csv(Count)
off_targets = pd.read_csv(NotLoc)
fig_oft = plot_offtarget(on_targets, off_targets, norm)

#====================Norm all=======================#
if norm == 'True':
    df = pd.read_csv(OncoprintNorm)
    fig_norm = plot_norm(df)

#====================Norm mean=====================#
if norm == 'True':
    df = pd.read_csv(OncoprintMeanNorm)
    fig_mean_norm = plot_mean_norm(df)

#===================Mannhatan======================#
if norm == 'True':
    df = pd.read_csv(OncoprintNorm)
    fig_manhattan = plot_manhattan(df)

#=====================PCA=========================#
if norm == 'True':
    finalDf = pd.read_csv(PCA_data)
    fig_pca = plot_pca(finalDf)

#====================SitePercent===================#
df = pd.read_csv(Oncoprint_All)
fig_percent_site = plot_site_percent(df)

#====================Boxplot=======================#
if norm == 'True':
    df = pd.read_csv(filtered_target)
    fig_boxplot = boxplot_site(df)
#======================NormSite=====================#
if norm == 'True':
    df = pd.read_csv(boxplot_csv)
    fig_site_norm = plot_site_norm(df)

#======================Command======================#
with open(c) as f:
    command = f.readline()

df = pd.read_csv(c)
df = df.reset_index()
df.columns = [ 'Parameter', 'Value']

fig_table = plot_options(df)

#==========================table_site======================#
df = pd.read_csv(filtered_target)
table_global = plot_site_table(df, 'percentage', 'None')
#==========================table_norm======================#
if norm == 'True':
    df = pd.read_csv(boxplot_csv)
    bed = pd.read_csv(filtered_target)
    table_zscore = plot_site_table(df, 'zscore', bed)
#======================mean_gene_table=====================#
df = pd.read_csv(filtered_target)
table_mean_gene = plot_table_mean_gene(df, 'methpercent')
#===================mean_gene_table_norm===================#
if norm == 'True':
    df = pd.read_csv(mean_gene_normalized)
    table_mean_gene_normalized = plot_table_mean_gene(df, 'zscore')
#========================TablePCA==========================#
if norm == 'True':
    df = pd.read_csv(PCA_data)
    bed = pd.read_csv(filtered_target)
    table_pca = plot_table_pca(df, bed)
#=========================DonutCGI=========================#
df = pd.read_csv(cgi)
figure_donut_cgi = plot_donut_cgi(df)
#=======================VolcanoPlot========================#
if norm == 'True':
    df = pd.read_csv(volcano)
    fig_volcano = plot_volcano(df)
#===========================SNV============================#
df = pd.read_csv(snv_count)
fig_count_snv = plot_count_snv(df)
#==========================HTML============================#

with open(Output + '/AutoMethyc_Report.html', 'w') as f:
    f.write(html_css())
    if norm == 'True':
        f.write(html_navbar_complete())
    else:
        f.write(html_navbar_sNorm())

    f.write(html_AutoMethyc(command))
    f.write(fig_table.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_base())
    f.write(fig_fastqc.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_depth())
    f.write(fig_depth.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_coverage())
    f.write(fig_oft.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_cgi())
    f.write(figure_donut_cgi.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_all())
    f.write(table_global.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(fig_all.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_mean_site())
    f.write(fig_percent_site.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_mean_gene())
    f.write(table_mean_gene.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(fig_mean.to_html(full_html=False, include_plotlyjs='cdn'))
    if norm == 'True':
        f.write(html_boxplot())
        f.write(fig_boxplot.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(html_norm())
        f.write(table_zscore.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig_norm.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(html_norm_manhattan())
        f.write(fig_manhattan.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(html_mean_site_norm())
        f.write(fig_site_norm.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(html_mean_gene_norm())
        f.write(table_mean_gene_normalized.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig_mean_norm.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(html_volcano())
        f.write(fig_volcano.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(html_pca())
        f.write(table_pca.to_html(full_html=False, include_plotlyjs='cdn'))
        f.write(fig_pca.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_snv())
    f.write(fig_count_snv.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_fooder())
print ('======================== done html_report =======================')
