#!/usr/bin/env python3
import sys
import pandas as pd

df_i = pd.read_csv(sys.argv[1], header = None, sep='\t')
ID = sys.argv[2]
output = sys.argv[3]
df_bd = pd.read_csv(sys.argv[4])
st = sys.argv[5]

df_i.columns = ['Chr','Start','End','Met_perc','Cyt_Met','Cyt_NoMet','Depth']
# flags
df_i.insert(0, 'Sample', [ID]*len(df_i))
df_i.insert(1, 'Status', [st]*len(df_i))

print(df_i)
#print(df_bd)
df_bd = pd.concat([df_bd, df_i])
df_bd = df_bd.set_index('Sample')

df_bd.to_csv(output+'/merge.csv')
