#!/usr/bin/env python
import pandas as pd
import sys

Input = sys.argv[1]
Output = sys.argv[2]

print ('#----------------Construct Oncoprint-------------------#')
merge_filtrado = pd.read_csv(Input)

merge_filtrado=merge_filtrado.drop(['End',  'Cyt_Met', 'Cyt_NoMet'], axis=1)

df = merge_filtrado.pivot(index=['Chr','Start','Gene'], columns=['Sample', 'Status'])

# Eliminar el multindice de las columnas
df = df.droplevel(level=0, axis=1)

df.to_csv(Output+'/Oncoprint.csv')

#Remplazar los valores numericos por 0
#df = df.fillna(0)
#df.to_csv(Output+'/OncoprintRellenado.csv')


print ('''

Output:
	Output/Oncoprint.csv
''')

print ('#----------------- Done Oncoprint--------------------#')

#-----------------------------------------------------------------------

print('')
print('#------------Init Construct Oncoprint Promedio -----------#')

# Eliminar el multindice
df = df.droplevel(level=0)
# Eliminar los indices
df_reset = df.reset_index()
df_reset = df_reset.drop(['Start'], axis = 1)

# Determinar los genes a graficar
gen = list(df_reset['Gene'].unique())

# Construcción de un df con las columnas anteriores
df_bd = pd.DataFrame(columns = df.columns)

for i in range(len(gen)):
	# Filtrar el df por gen
	df_reset_i = df_reset[df_reset['Gene'] == gen[i] ]
	# Calcular la media por paciente de cada gen
	x= df_reset_i.mean()
	list = x.tolist()
	# Agregar fila por fila correspondiente a cada gen de todas las muestras
	df_bd.loc[i]=list

# Insertat la columna de genes
df_bd.insert(0, 'Gene', gen)
df_bd = df_bd.set_index('Gene')
df_bd.to_csv(Output+'/OncoprintPromedio.csv')

print ('')
print('Output: OncoprintPromedio.csv')
print('')

print('#----------------Done--------------------#')
