#!/usr/bin/env python3
#import os
#os.environ['OPENBLAS_NUM_THREADS'] = '1'

import pandas as pd
import sys

Input = sys.argv[1]
Output = sys.argv[2]

df = pd.read_csv(Input)
df = df.drop(['End',  'Cyt_Met', 'Cyt_NoMet', 'Depth'], axis=1)
print(df)
count = df['Sample'].value_counts()

Onco = df.pivot(index=['Chr', 'Start'], columns = ['Sample', 'Status'])
#Onco = Onco.droplevel(level=0, axis=1)
print(Onco)
count.to_csv(Output+'/Count.csv')
Onco.to_csv(Output+'/Oncoprint.csv')
