#!/usr/bin/python
# coding: utf-8

# # Rerport HTML

import pandas as pd
import plotly.express as px
from IPython.display import HTML
import sys
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import numpy as np

input_folder = sys.argv[1]
Output = sys.argv[2]

Oncoprint_All = input_folder+'/CSV/Oncoprint_wf.csv'
Count = input_folder+'/CSV/Count.csv'
bed = input_folder+ '/CSV/StatusCpG.csv'
depth = input_folder + '/CSV/CountUF_depth.csv'
fastqc = input_folder + '/CSV/fastqc_merge.csv'

print('#-------------------Plotting-------------------------')

#---------------------------fastqc---------------------------
df = pd.read_csv(fastqc)
df['Mean'] = list(map(float, df.Mean))
df = df.replace({'65-69': 67, '75-79': 77, '80-84': 82, '85-89': 87, '90-94': 92,
                      '100-104': 102, '105-109': 107, '110-114':112, '115-119': 117,
                       '120-124': 122, '125-129': 127, '130-134': 132, '135-139':137,
                       '140-144': 142, '145-149': 147, '150-154': 152, '155-159': 157,
                       '70-74': 72, '95-99': 97, '60-64': 62, '10-14': 12, '55-59': 57,
                       '15-19': 17, '25-29': 27, '30-34': 32, '35-39': 37, '40-44': 42,
                       '45-49': 47, '50-54':52, '20-24': 22, '195-199': 197, '220-224': 222,
                       '215-219': 217, '210-214': 212, '205-209': 207, '200-204': 202,
                       '175-179': 177, '190-194': 192, '185-189': 187, '180-184':182,
                       '170-174':172, '165-169': 167, '160-164': 162, '10-14': 12
                      })
df['#Base'] = list(map(int, list(df['#Base'])))
df = df.rename(columns = {'#Base':'Position (pb)', 'Mean': 'Phred Score'})

fig_fastqc = px.line(df_bd, x="Position (pb)", y="Phred Score", color='ID')
fig_fastqc.add_hrect(y0=28, y1=40, line_width=0, fillcolor="green", opacity=0.2)
fig_fastqc.add_hrect(y0=20, y1=28, line_width=0, fillcolor="yellow", opacity=0.2)
fig_fastqc.add_hrect(y0=0, y1=20, line_width=0, fillcolor="red", opacity=0.2)
fig_fastqc.update_layout(showlegend=False)

#---------------------------Depth--------------------------
df = pd.read_csv(depth)
longitud_inicial = len(df)
longitud_final = longitud_inicial * 2

lst =[]
typ = []
ID = []

for i, j, z in zip(df.filtered, df.unfiltered, df.ID):
    lst.append(i)
    typ.append('filtered')
    lst.append(j)
    typ.append('unfiltered')
    lI = [z] * 2
    ID = ID + lI

while longitud_inicial < longitud_final:
    df.loc[len(df.index)] = ['NaN'] * len (df.columns)

    longitud_inicial = longitud_inicial + 1

df['Count'] = lst
df['Type'] = typ
df['ID'] = ID

fig_depth = px.bar(df, x="ID", y="Count", color="Type")

#------------------------All_sites----------------------
sites_bed = pd.read_csv(bed)
df = pd.read_csv(Oncoprint_All)

df.columns = list(df.loc[0, :])
df = df.drop(df.index[[0, 1, 2]])
df = df.rename(columns = {'Sample':'Chr', np.nan:'Start'})

lst = []
site = []

for j in df.Start:
    for i,k,c in zip(sites_bed.Site, sites_bed.Type, sites_bed.chrom):
        if int(j) == int(i):
            lst.append(k)
            site.append(str(c) + ':' + str(i))

# Remplazar los valores
lst = list(map(lambda x: x.replace('CpG island', '0'), lst))
lst = list(map(lambda x: x.replace('CpG shore', '1'), lst))
lst = list(map(lambda x: x.replace('CpG shelf', '2'), lst))
lst = list(map(lambda x: x.replace('CpG inter CGI', '3'), lst))

merge = []
for i,j in zip(df.Chr, df.Start):
    merge.append(str(i) + ':' + str(j))
df['SiteCpG'] = merge
df = df.set_index('SiteCpG')
df = df.drop(['Chr', 'Start'], axis=1)

df_annot = pd.DataFrame({'SiteCpG': site, 'Type':lst})
df_annot = df_annot.set_index('SiteCpG')

# Make array
z = np.array([list(df_annot.Type)]).T

def discrete_colorscale(bvals, colors):
    if len(bvals) != len(colors)+1:
        raise ValueError('len(boundary values) should be equal to  len(colors)+1')
    bvals = sorted(bvals)
    nvals = [(v-bvals[0])/(bvals[-1]-bvals[0]) for v in bvals]  #normalized values

    dcolorscale = [] #discrete colorscale
    for k in range(len(colors)):
        dcolorscale.extend([[nvals[k], colors[k]], [nvals[k+1], colors[k]]])
    return dcolorscale

if len(list(df_annot['Type'].value_counts())) == 3:
    bvals = [0, 1, 2, 3]
    colors = ['blue', '#3efe00', 'red']
    dcolorsc = discrete_colorscale(bvals, colors)
    heatmap = go.Heatmap(z=z, colorscale = dcolorsc,
                     colorbar = dict(thickness=10,
                                     tickvals=[0.2, 1, 1.7],
                                     ticktext=['a', 'b', 'c']), x = ['CGI'], y = list(df.index)
                    )
    fig1 = px.imshow(df, color_continuous_scale='RdBu_r')
    #ff.create_annotated_heatmap(z1, x.tolist(), y.tolist(),  colorscale='matter')
    fig2 = go.Figure(data=[heatmap])


    fig = make_subplots(
        rows=1, cols=2,
        horizontal_spacing=0.05,
        column_widths=[0.9, 0.1], shared_yaxes=True
    )

    fig.add_trace(fig1.data[0], 1, 1)
    fig.add_trace(fig2.data[0], 1, 2)


    fig.add_annotation(text='CpG island                CpG shore                CpG shelf',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.3,
                        y=-0.13,
                        borderwidth=1)

    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.28,
                        y=-0.126,
                        bgcolor=colors[0],
                        borderwidth=7)
    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.41,
                        y=-0.126,
                        bgcolor=colors[1],
                        borderwidth=7)
    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.525,
                        y=-0.126,
                        bgcolor=colors[2],
                        borderwidth=7)
else:
    bvals = [0, 1, 2, 3 ,4]
    colors = ['blue', '#3efe00', 'red', '#00fec0']
    x = list(range(len(list(df_annot['Type'].value_counts()))+1))
    dcolorsc = discrete_colorscale(x, colors[0:len(list(df_annot['Type'].value_counts()))])

    heatmap = go.Heatmap(z=z, colorscale = dcolorsc,
                     colorbar = dict(thickness=10,
                                     tickvals=[0.2, 1, 1.7, 2.2],
                                     ticktext=['a', 'b', 'c' ,'d']), x = ['CGI'], y = list(df.index)
                    )
    fig1 = px.imshow(df, color_continuous_scale='RdBu_r')
    fig2 = go.Figure(data=[heatmap])


    fig = make_subplots(
        rows=1, cols=2,
        horizontal_spacing=0.05,
        column_widths=[0.9, 0.1], shared_yaxes=True
    )

    fig.add_trace(fig1.data[0], 1, 1)
    fig.add_trace(fig2.data[0], 1, 2)


    fig.add_annotation(text='CpG island                CpG shore                CpG shelf                CpG inter CGI',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.3,
                        y=-0.13,
                        borderwidth=1)

    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.28,
                        y=-0.126,
                        bgcolor=colors[0],
                        borderwidth=7)
    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.41,
                        y=-0.126,
                        bgcolor=colors[1],
                        borderwidth=7)
    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.525,
                        y=-0.126,
                        bgcolor=colors[2],
                        borderwidth=7)
    fig.add_annotation(text='',
                        align='left',
                        showarrow=False,
                        xref='paper',
                        yref='paper',
                        x=0.64,
                        y=-0.126,
                        bgcolor=colors[3],
                        borderwidth=7)
fig_all = fig
#fig_all.update_layout(paper_bgcolor="#1c1f27", template =  "plotly_dark")

#-----------------------------HTML-------------------------
html_head = '''
<html>
    <head>
        <style>
            body{ margin:0; background:white; color:black; font-family: Arial;}
            .active {
                background-color: #04AA6D;
                color: white;
                }

            /* Vertical bar */
            ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
                width: 13%;
                background-color: #1c1f27;
                height: 100%; /* Full height */
                position: fixed; /* Make it stick, even on scroll */
                overflow: auto; /* Enable scrolling if the sidenav has too much content */
                }
            li a {
                display: block;
                color: #ffffff;
                padding: 8px 16px;
                text-decoration: none;
                }

            /* Change the link color on hover */
            li a:hover {
            background-color: #04aa6d;
            color: white;
            }

            .main{
            margin-left: 15%;
            padding: 1px 16px;
            height 500px;
            }

            .fraction {
                display: inline-block;
                vertical-align: middle;
                margin: 0 0.2em 0.4ex;
                text-align: center;
                }

            .fraction > span {
            display: block;
            padding-top: 0.15em;
            }

            .fraction span.fdn {border-top: thin solid white;}
            .fraction span.bar {display: none;}

        </style>
    </head>

    <body>
        <ul class="vertical">
            <li><a style="background-color:#009DCF; color:white"> AutoMethyc </a></li>
            <li><a href="#Home"> Home </a></li>
            <li><a href="#Depth"> Depth </a></li>
            <li><a href="#All"> Heatmap all</a></li>
            <li><a href="#about"> About </a></li>
        </ul>

        <div class="main">
            <h1 id="Home"> AutoMethyc </h1>
                <h2> Version without normal samples </h2>
                    AutoMethyc is a pipeline automated which aims for simplicity and practcality in methylation analysis.
                <h2 id="Depth"> Depth </h2>
                    Count of sites filtered and unfiltered variables by depth
        </div">
    </body>
'''

html_spec1 = '''
    <body>
        <h2 id="All"> Heatmap all sites </h2>
            Heatmap of the percentage of methylation present at each site present in the bedGraph per sample
    </body>
'''

html_fooder = '''
    <body>
        <h3 id="about"> Repository  </h4>
            This program is avalible in <td><a href="https://github.com/FerAmbriz/AutoMethyc"> AutoMethyc </a></td>
    </body>
</html>'''


# 3. Write the html string as an HTML file
with open(Output + '/AutoMethyc_Report.html', 'w') as f:
    f.write(html_head)
    f.write(fig_fastqc.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(fig_depth.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_spec1)
    f.write(fig_all.to_html(full_html=False, include_plotlyjs='cdn'))
    f.write(html_fooder)
