#!/bin/bash

input_bam=$1
ref=$2
output=$3
threads=$4

#start=`date +%s`

#---------------------- Reference Dictionary ---------------------#
ref_folder=${ref%/*}
reference_name=${ref##*/}
reference_name=${reference_name%.*}

array=($(ls $ref_folder/$reference_name*))

reference_dict=${ref%.*}.dict

if [[  " ${array[*]} " =~ " ${reference_dict} " ]]; then
  echo '================= starting with variant calling =================='
else
  echo '============ Generating reference genome dictionary =============='
  gatk CreateSequenceDictionary -R $ref
  echo '================= starting with variant calling =================='
fi
#-------------------------- processing --------------------------#

mkdir $input_bam/tmp
mkdir $input_bam/preprocessing

for i in $input_bam/*.bam;
do
  echo $i 
  
  ID=${i%_S*}; ID=${ID##*/}; prefix='one_mismatch.'; ID=${ID/#$prefix}

  samtools sort -@ $threads $i -o $input_bam/preprocessing/${ID}_sorted.bam
  samtools calmd -@ $threads -b $input_bam/preprocessing/${ID}_sorted.bam $ref 1> $input_bam/preprocessing/${ID}_calmd.bam 2> /dev/null
  samtools index -@ $threads $input_bam/preprocessing/${ID}_calmd.bam

  revelio -t $input_bam/tmp --threads $threads -f $ref $input_bam/preprocessing/${ID}_calmd.bam $input_bam/preprocessing/${ID}_mask.bam
  
  samtools addreplacerg -r '@RG\tID:'${ID}'\tSM:'${ID} $input_bam/preprocessing/${ID}_mask.bam -o $input_bam/preprocessing/${ID}_mask.bam
  samtools index -@ $threads $input_bam/preprocessing/${ID}_mask.bam

done

arr=($(ls $input_bam/preprocessing/*_mask.bam))

extract_values (){
  arr2=()
  while [ $termina -ge $contador ]
  do
    arr2+=(${arr[$contador]})
    let contador=$contador+1
  done
}

for (( i=0; i<${#arr[@]}; i=i+$threads));
do
  contador=$i && termina=$(($i + $(($threads - 1))))
  extract_values

  for j in ${arr2[@]};
  do
    ID=${j%_mask*}
    ID=${ID##*/}
    gatk HaplotypeCaller -R $ref --native-pair-hmm-threads 2 -I $input_bam/preprocessing/${ID}_mask.bam -O $output/${ID}_mask_haplotype2.vcf &
  done
  wait
done
echo '====================== done revelio_haplotype ====================='
