#!/bin/bash

input_bam=$1
ref=$2
output=$3
threads=$4

ref_folder=${ref%/*}
reference_name=${ref##*/}
reference_name=${reference_name%.*}

array=($(ls $ref_folder/$reference_name*))

reference_dict=${ref%.*}.dict

if [[  " ${array[*]} " =~ " ${reference_dict} " ]]; then
  echo 'Starting with processing'
else
  echo 'Generating reference genome dictionary'
  gatk CreateSequenceDictionary -R $reference
fi

mkdir $output/tmp

for i in $input_bam/*bam;
do
  echo 'Starting variant call to ...'
  echo $i 
  
  
  ID=${i%_S*}
  ID=${ID##*/}
  prefix='one_mismatch.'
  ID=${ID/#$prefix}

  samtools sort -@ $threads $i -o $output/${ID}_sorted.bam
  samtools calmd -@ $threads -b ${ID}_sorted.bam $ref 1> ${ID}_calmd.bam 2> /dev/null
  samtools index -@ $threads ${ID}_calmd.bam

  revelio -t $output/tmp --threads $threads -f $ref ${ID}_calmd.bam ${ID}_mask.bam
  
  samtools addreplacerg -r '@RG\tID:'${ID}'\tSM:'${ID} ${ID}_mask.bam -o ${ID}_mask.bam
  samtools index -@ $threads ${ID}_mask.bam

  gatk HaplotypeCaller -R $ref --native-pair-hmm-threads $threads -I ${ID}_mask.bam -O ${ID}_mask_haplotype2.vcf

done

echo 'Done'
