#!/usr/bin/env python3
# coding: utf-8
#import os
#os.environ['OPENBLAS_NUM_THREADS'] = '1'
import pandas as pd
import numpy as np
import sys

df_type_allsites = pd.read_csv(sys.argv[1])
output = sys.argv[2]
df_gene = pd.read_csv(sys.argv[3])

print ('============== making long format matrix normalized ==============')
#----------------------------- mean gene norm ----------------------------#
columns_gene = list(df_gene.columns)
columns_gene = columns_gene[2:len(columns_gene)]
df_gene = pd.melt(df_gene, id_vars=['ID', 'Type'], value_vars=columns_gene)
print(df_gene)
df_gene = df_gene.set_index('ID')
df_gene.to_csv(output+'/mean_gene_normalized.csv')

#----------------------------- all sites norm ----------------------------#
columns_type = list(df_type_allsites.columns)
columns_type = columns_type[2:len(columns_type)]

df_type = pd.melt(df_type_allsites, id_vars=['ID', 'Type'], value_vars=columns_type)

print(df_type)
df_type = df_type.set_index('ID')

df_type.to_csv(output+'/filtered_target_normalized.csv')
print ('================ done unpivot_matrix_normalized ================')
